### ISSUE TITLE
Problems with cursor location in PSRmeote

### ISSUE THREAD

**Issue by wigster** [JanDeDobbeleer/oh-my-posh2#182] opened 2019-11-11 09:54 UTC
Thanks for fixing the missing $profile problem #168. 

I can now successfully import oh-my-posh on the remote machine and set themes, which are properly reflected in the local terminal. However, there are problems with the cursor location after executing commands remotely. It always returns to the first line of the terminal, while the output extends many lines down. Executing a new command overwrites this output.

The remote machine is a Windows 2012R2 server with PS 5.1. The local machine is a latest Windows 10 1909. This happens both in the standard Powershell console and the Windows Terminal preview. The remote machine's oh-my-posh is version 2.0.332.

**Comment by JanDeDobbeleer** [comment] 2019-11-13 10:49
Do you happen to have a screenshot of this?

**Comment by wigster** [comment] 2019-11-13 11:00
Have a look here:

![image](https://user-images.githubusercontent.com/10956987/68757754-c2745700-060c-11ea-8f46-796ce89b4cf5.png)

This is the posh window in WinTemrinal after remoting into the pornogrubas server and setting the theme to Darkblood. I have to say that the default theme works ok, but Agnoster and Paradox also do this.

The remote profile is empty apart from  my having Import-Moduled oh-my-posh

**Comment by JanDeDobbeleer** [comment] 2019-11-13 11:09
Interesting, I wonder if it's because that server can't handle the symbols. I will try to reproduce this in order to debug.

**Comment by wigster** [comment] 2019-11-13 11:19
It's true that when run locally on the server, you get similarly (bad) behaviour.

**Comment by JanDeDobbeleer** [comment] 2020-10-11 07:57
Can you confirm this still occurs in V3? https://ohmyposh.dev

**Comment by wigster** [comment] 2020-10-12 09:48
Hi,
v3 seems to require PS 6.0+ (you don't say this in the docs though), so I cannot quite replicate what I was doing with the 5.1.

But for PS 7.0.3 installed on WS2012R2 and OMP 3.13 there is still an issue, but different. When I set a prompt locally on the Windows Server in the standard terminal window, I get "The parameter is incorrect." as the prompt. Not sure how to get more information here.

On the other hand, when I remote in from a Win10 machine into PS 7.0.3 on the WS2012 R2 server (from both PS 5.1 and PS7.0.3 and from both the standard Windows terminal and the new WinTerminal) I get the following error when I import OMP

```
PS C:\Users\Admin> import-module oh-my-posh

ParentContainsErrorRecordException: C:\Users\Admin\Documents\PowerShell\Modules\oh-my-posh\3.13.0\oh-my-posh.psm1:28
Line |
  28 |      [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception setting "OutputEncoding": "The handle is invalid."
Import-Module: The module to process 'oh-my-posh.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest 'C:\Users\Admin\Documents\PowerShell\Modules\oh-my-posh\3.13.0\oh-my-posh.psd1' was not processed because no valid module was found in any module directory.
```

**Comment by JanDeDobbeleer** [comment] 2020-10-12 14:38
Can you check with `3.14.2`?

**Comment by wigster** [comment] 2020-10-12 15:00
It's the same locally on WS2012R. Remotely I get a nice error on Import-module

```
oh-my-posh: unable to set output encoding to UTF8, fonts might be rendered incorrectly.
```
And then it doesn't do anything once I try to set the theme (but no errors either)

**Comment by JanDeDobbeleer** [comment] 2020-10-12 16:54
I print that statement but everything should continue with the side effect of having garbled fonts. No idea why it doesn't do anything correctly, in theory ot should work like a local prompt.

Unless it's not actually a console and the prompt function doesn't exist. In that case there's not much I can do.

**Comment by JanDeDobbeleer** [comment] 2020-10-12 16:58
Or wait this could be related to being admin I suppose. There's a whole lot of trouble when installing as admin, not sure why just yet.

**Comment by B4Art** [comment] 2020-12-07 10:56
> Or wait this could be related to being admin I suppose. There's a whole lot of trouble when installing as admin, not sure why just yet.

Could be the way you import the module. There are many options.
In elevated (admin) mode:
-Scope AllUsers places the module in C:\Windows\Powershell\Modules
-Scope CurrentUser places the module in C:\Users\<Username>\Documents\Powershell\Modules
If you do both the CurrentUser place is used by default.
The theme-path itself also are different:
C:\Program Files\PowerShell\Modules\oh-my-posh\<oh-my-posh-version>\Themes
C:\Users\<Username>\Documents\Powershell\PoshThemes

**Comment by JanDeDobbeleer** [comment] 2020-12-07 14:20
This was specifically related to UTF8 which made it so the rendering of the icons/font wasn't correctly. Now, in the meantime A LOT has changed in terms of invocation so the issue could be gone.

**Comment by JanDeDobbeleer** [comment] 2021-01-19 18:24
Closing this due to archiving V2 before EOM.

**Closed as completed by JanDeDobbeleer** 2021-01-19 18:24 UTC
