### ISSUE TITLE
Handling paths with Square brackets

### ISSUE THREAD

**Issue by arnabanimesh** [JanDeDobbeleer/oh-my-posh2#249] opened 2020-05-18 18:25 UTC
If a directory contains Square Brackets, then it shows up as a funny prompt, which can be seen in this image:
![image](https://user-images.githubusercontent.com/6032584/82246691-cb026d00-9962-11ea-9ae4-8c9e9b8a272e.png)

**Comment by eirikhoe** [comment] 2020-05-24 21:37
This is not true in general. As long as you escape the square brackets properly when entering the folder the prompt works just fine for me.
![Merknad 2020-05-24 233342](https://user-images.githubusercontent.com/57374889/82765448-76099f80-9e17-11ea-81d3-7285c4f133fe.png)

**Comment by arnabanimesh** [comment] 2020-05-24 22:29
Note this screenshot:
![image](https://user-images.githubusercontent.com/6032584/82766337-e2969580-9e3b-11ea-9c1b-988ac87c6c67.png)

**Comment by eirikhoe** [comment] 2020-05-25 00:31
Thanks. I am able to reproduce it now. It is not an issue of the path containing square brackets. It is an issue of the path containing a left square bracket, `[`, without an accompanying right square bracket to close it. So the folder names `[y]` and `y]` are fine, but `[y` triggers the error.  

![Merknad 2020-05-25 023815](https://user-images.githubusercontent.com/57374889/82768697-ed97f880-9e30-11ea-94e9-9fd93e35ae7b.png)

Likely a parsing issue where the bracket gets interpreted as code internally somewhere, but I don't know the repo well enough to figure out where.

**Comment by eirikhoe** [comment] 2020-05-25 01:01
Worth noting that you do enter the folder and things work normally besides the weird prompt. It also seems to be limited to a subset of the Themes. I cannot reproduce it on Paradox, Darkblood, or my own custom theme (based on Sorin), but it affects Agnoster and Sorin. 

Update: Realized it might have to do with whether the theme abbreviates the path or not and it is. It is an issue with the `Get-ShortPath` procedure. If a theme uses `Get-FullPath` it is not affected.

**Comment by eirikhoe** [comment] 2020-05-25 01:31
So I think I might have stumbled onto the issue. Line 95 in `Prompt.ps1`

`return (Test-Path -Path "$($Path)\.git") -Or (Test-Path -Path "$($Path)\.hg") -Or (Test-Path -Path "$($Path)\.svn")`

 should use `-LiteralPath` so the `$Path` variable doesn't get interpreted. If I change it to

`return (Test-Path -LiteralPath "$($Path)\.git") -Or (Test-Path -LiteralPath "$($Path)\.hg") -Or (Test-Path -LiteralPath "$($Path)\.svn")`

it fixes the issue.

Before:

![Merknad 2020-05-25 032857](https://user-images.githubusercontent.com/57374889/82770220-02c45580-9e38-11ea-9d4c-3128fa1df70d.png)

After:

![Merknad 2020-05-25 032937](https://user-images.githubusercontent.com/57374889/82770230-09eb6380-9e38-11ea-8645-adcfb04cad1c.png)

I'd submit a pull request, but I am not well versed enough in PowerShell or this repo to know if this has any potential downsides or side effects, though I wouldn't think so.

**Comment by arnabanimesh** [comment] 2020-05-25 06:47
Just submit a pull request, then others can also test it. Either it will be accepted or modified. What's the harm? If it has any downside (which I do not think it should have any, since literalpath is just returning a string), the change can be easily reverted later on.

Also, it is a legacy cmdlet supported since PowerShell 2.

**Closed as completed** 2020-06-05 09:59 UTC
